;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  File name    : T_COM386.ASM                                                 ;
;                                                                              ;
;  Title        : OS/2 API trace DLL common Intel assembly routines            ;
;                                                                              ;
;  Author       : Dave Blaschke                                                ;
;                 deblaschke@yahoo.com                                         ;
;                                                                              ;
;  Description  : Common    Intel    assembly    routines:       GetAPICaller, ;
;                 GetAPICaller16, T_GetTID, T_RestoreRegs16, and T_SaveRegs16. ;
;                                                                              ;
;  Notes        : T_SaveRegs16 and T_RestoreRegs16  are required by all 16-bit ;
;                 Dos  APIs  because  of  an  undocumented  "feature"  of  the ;
;                 Microsoft  C  compiler.  Even  though  the 16-bit  OS/2  API ;
;                 calling convention does not  preserve CX or DX across an API ;
;                 call,  the Microsoft compiler  assumes that  these registers ;
;                 are preserved  across a call  directly into the  OS/2 kernel ;
;                 through a  call gate  because  the  register state  is saved ;
;                 upon entry  into the kernel and restored  upon exit from the ;
;                 kernel.  Unfortunately,  the  thunks  generated  by the  IBM ;
;                 VisualAge C++ compiler use ECX and EDX.                      ;
;                                                                              ;
;                 In a similar fashion,  T_SaveRegs16  and T_RestoreRegs16 are ;
;                 also required by all 16-bit Kbd, Mou, Vio APIs because most, ;
;                 if not all,  of these APIs perform a PUSHA  upon entry and a ;
;                 POPA  upon exit  even  though  the 16-bit  OS/2 API  calling ;
;                 convention does  not preserve  CX or DX  across an API call. ;
;                 Because some OS/2 applications,  such as TEDIT, know that CX ;
;                 and DX are preserved across these API calls,  they depend on ;
;                 the state  of one or  both of these  registers.  Once again, ;
;                 the thunks  generated by the IBM VisualAge C++  compiler use ;
;                 ECX and EDX.                                                 ;
;                                                                              ;
;                 As a result  of the above,  T_SaveRegs16  must be  the first ;
;                 code executed  when entering a 16-bit Dos,  Kbd, Mou, or Vio ;
;                 trace API,  and T_RestoreRegs16 must be executed immediately ;
;                 before the return statement  when exiting a 16-bit Dos, Kbd, ;
;                 Mou, or Vio trace API.                                       ;
;                                                                              ;
;  History      : Version Date    Item                                         ;
;                 2.30.00 12Jun95 Created (supported LX format  and 32-bit Dos ;
;                                 APIs only)                                   ;
;                 2.30.13 27Aug95 Added OS/2 for PowerPC support               ;
;                 2.40.17 21Apr97 Added 16-bit Dos APIs                        ;
;                 2.40.18 30Apr97 Added 16-bit Kbd APIs                        ;
;                 2.40.21 20May97 Fixed/minimized 16-bit stack usage           ;
;                 2.40.50 06Feb98 Fixed CX  and DX  corruption by  16-bit Kbd, ;
;                                 Mou, and Vio APIs                            ;
;                 2.40.80 02Dec98 Added undocumented -DUMPSTACK option         ;
;                 2.45.31 26Jun01 Added  capability  of building  32-bit  only ;
;                                 trace DLLs                                   ;
;                 2.45.39 10Oct10 Preserved FS in T_GetTID                     ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        .386P

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  External function declarations                                              ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

EXTRN   DOS32SELTOFLAT:NEAR
EXTRN   DOS32FLATTOSEL:NEAR

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  Structure declarations                                                      ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
regs16_s                STRUC                   ; 16-bit registers
regs16_usParmBytes      DW      ?               ; Parameter bytes
regs16_usCX             DW      ?               ; CX
regs16_usDX             DW      ?               ; DX
regs16_ulCSIP           DD      ?               ; CS:IP
regs16_s                ENDS
ENDIF

tib_s                   STRUC
tib_pexchain            DD      ?
tib_pstack              DD      ?
tib_pstacklimit         DD      ?
tib_ptib2               DD      ?
tib_version             DD      ?
tib_ordinal             DD      ?
tib_s                   ENDS

tib2_s                  STRUC
tib2_ultid              DD      ?
tib2_ulpri              DD      ?
tib2_version            DD      ?
tib2_usMCCount          DW      ?
tib2_fMCForceFlag       DW      ?
tib2_s                  ENDS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  Segment definitions                                                         ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

CODE32  SEGMENT DWORD USE32 PUBLIC 'CODE'
CODE32  ENDS
IFDEF T_16BIT
CODE16  SEGMENT WORD USE16 PUBLIC 'CODE'
CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  GetAPICaller()                                                              ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        PUBLIC  GetAPICaller

        ASSUME  CS:FLAT
CODE32  SEGMENT
        ALIGN   04H

GetAPICaller    PROC
        MOV     EAX, [EBP]                      ; EAX = API caller's EBP
        MOV     EAX, [EAX+4]                    ; EAX = API caller's return EIP
        RET
GetAPICaller    ENDP

CODE32  ENDS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  GetAPICaller16()                                                            ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        PUBLIC  GetAPICaller16

        ASSUME  CS:FLAT
CODE32  SEGMENT
        ALIGN   04H

GetAPICaller16  PROC
        MOV     EAX, [EBP]                      ; EAX = Trace API's call frame
        MOV     EAX, [EAX+4]                    ; EAX = API thunk's call frame
        MOV     EAX, [EAX]                      ; EAX = API caller's SS:BP
        CALL    DOS32SELTOFLAT                  ; EAX = API caller's EBP
        MOV     EAX, [EAX+12]                   ; EAX = API caller's return CS:IP
        RET
GetAPICaller16  ENDP

CODE32  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  GetAPICallerStackFrame()                                                    ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        PUBLIC  GetAPICallerStackFrame

        ASSUME  CS:FLAT
CODE32  SEGMENT
        ALIGN   04H

GetAPICallerStackFrame  PROC
        MOV     EAX, [EBP]                      ; EAX = API caller's stack frame
        RET
GetAPICallerStackFrame  ENDP

CODE32  ENDS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  GetAPICallerStackFrame16()                                                  ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        PUBLIC  GetAPICallerStackFrame16

        ASSUME  CS:FLAT
CODE32  SEGMENT
        ALIGN   04H

GetAPICallerStackFrame16        PROC
        MOV     EAX, [EBP]                      ; EAX = Trace API's call frame
        MOV     EAX, [EAX+4]                    ; EAX = API thunk's call frame
        MOV     EAX, [EAX]                      ; EAX = API caller's SS:BP
        ADD     EAX, 12                         ; EAX = API caller's return CS:IP pointer
        RET
GetAPICallerStackFrame16        ENDP

CODE32  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  T_GetTID()                                                                  ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        PUBLIC  T_GetTID

        ASSUME  CS:FLAT
CODE32  SEGMENT
        ALIGN   04H

T_GetTID        PROC
        PUSH    FS                              ; Save FS
        PUSH    150BH                           ; Push TIB selector
        POP     FS                              ; FS = TIB selector
        MOV     EAX, FS:[tib_ptib2]             ; EAX = TIB2 pointer
        MOV     EAX, [EAX].tib2_ultid           ; EAX = Thread identifier
        POP     FS                              ; Restore FS
        RET
T_GetTID        ENDP

CODE32  ENDS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  T_RestoreRegs16()                                                           ;
;                                                                              ;
;  Upon entry EAX  contains the flat address of the  saved registers structure ;
;  because  T_RestoreRegs16 is not  declared as APIENTRY  in t_common.h.  As a ;
;  result,  the first parameter is passed to this routine in EAX instead of on ;
;  the stack.  All T_RestoreRegs16 does is  convert the structure's address to ;
;  16-bit and move it into EDX for the appropriate RestoreRegs below.          ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        PUBLIC  T_RestoreRegs16

        ASSUME  CS:FLAT
CODE32  SEGMENT
        ALIGN   04H

T_RestoreRegs16 PROC
IFDEF T_16BIT
        CALL    DOS32FLATTOSEL                  ; EAX = 16-bit sRegs16 pointer
        MOV     EDX, EAX                        ; EDX = 16-bit sRegs16 pointer
ENDIF
        RET
T_RestoreRegs16 ENDP

CODE32  ENDS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  T_SaveRegs16()                                                              ;
;                                                                              ;
;  Upon entry EAX  contains the flat address of the  saved registers structure ;
;  because  T_SaveRegs16  is not  declared as  APIENTRY  in t_common.h.  As  a ;
;  result,  the first parameter is passed to this routine in EAX instead of on ;
;  the stack.  T_SaveRegs16  initializes  the structure  and replaces  the API ;
;  caller's return CS:IP with the CS:IP of the appropriate RestoreRegs below.  ;
;                                                                              ;
;  NOTE: The "SHL ECX, 5" instruction is  dependent upon the alignment and the ;
;  ordering of the RestoreRegs routines  below.  The calculation is the number ;
;  of API parameter bytes  divided by two  multiplied  by the alignment.  This ;
;  requires  that the  RestoreRegs routines  be ordered sequentially  starting ;
;  with zero (RestoreRegs00) and that there be a RestoreRegs routine for every ;
;  two-byte increment.                                                         ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

        PUBLIC  T_SaveRegs16

        ASSUME  CS:FLAT
CODE32  SEGMENT
        ALIGN   04H

T_SaveRegs16    PROC
IFDEF T_16BIT
        PUSH    EBX                             ; Save EBX
        MOV     EBX, EAX                        ; EBX = sRegs16 pointer
        MOV     [EBX].regs16_usCX, CX           ; Save CX in sRegs16
        MOV     [EBX].regs16_usDX, DX           ; Save DX in sRegs16
        MOV     EAX, [EBP+4]                    ; EAX = API thunk's call frame
        MOV     EAX, [EAX]                      ; EAX = API caller's SS:BP
        CALL    DOS32SELTOFLAT                  ; EAX = API caller's EBP
        PUSH    EAX                             ; Save API caller's EBP
        MOV     EAX, [EAX+12]                   ; EAX = API caller's return CS:IP
        MOV     [EBX].regs16_ulCSIP, EAX        ; Save CS:IP in sRegs16
        MOV     EAX, OFFSET FLAT:RestoreRegs00  ; EAX = RestoreRegs00 EIP
        MOVZX   ECX, [EBX].regs16_usParmBytes   ; ECX = Parameter bytes
        SHL     ECX, 5                          ; ECX = ( Parm bytes / 2 ) * 64
        ADD     EAX, ECX                        ; EAX = RestoreRegsXX EIP
        CALL    DOS32FLATTOSEL                  ; EAX = RestoreRegsXX CS:IP
        MOV     ECX, EAX                        ; ECX = RestoreRegsXX CS:IP
        POP     EAX                             ; EAX = API caller's EBP
        MOV     [EAX+12], ECX                   ; Return to RestoreRegsXX instead of caller
        POP     EBX                             ; Restore EBX
ENDIF
        RET
T_SaveRegs16    ENDP

CODE32  ENDS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs00()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs00 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  0 bytes of parameters.                                                      ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs00   PROC
        SUB     SP, 4                           ; Allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF
RestoreRegs00   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs02()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs02 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  2 bytes of parameters.                                                      ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs02   PROC
        SUB     SP, 6                           ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    2
RestoreRegs02   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs04()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs04 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  4 bytes of parameters.                                                      ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs04   PROC
        SUB     SP, 8                           ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    4
RestoreRegs04   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs06()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs06 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  6 bytes of parameters.                                                      ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs06   PROC
        SUB     SP, 10                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    6
RestoreRegs06   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs08()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs08 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  8 bytes of parameters.                                                      ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs08   PROC
        SUB     SP, 12                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    8
RestoreRegs08   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs10()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs10 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  10 bytes of parameters.                                                     ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs10   PROC
        SUB     SP, 14                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    10
RestoreRegs10   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs12()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs12 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  12 bytes of parameters.                                                     ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs12   PROC
        SUB     SP, 16                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    12
RestoreRegs12   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs14()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs14 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  14 bytes of parameters.                                                     ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs14   PROC
        SUB     SP, 18                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    14
RestoreRegs14   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs16()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs16 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  16 bytes of parameters.                                                     ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs16   PROC
        SUB     SP, 20                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    16
RestoreRegs16   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs18()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs18 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  18 bytes of parameters.                                                     ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs18   PROC
        SUB     SP, 22                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    18
RestoreRegs18   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs20()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs20 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  20 bytes of parameters.                                                     ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs20   PROC
        SUB     SP, 24                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    20
RestoreRegs20   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs22()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs22 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  22 bytes of parameters.                                                     ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs22   PROC
        SUB     SP, 26                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    22
RestoreRegs22   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs24()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs24 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  24 bytes of parameters.                                                     ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs24   PROC
        SUB     SP, 28                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    24
RestoreRegs24   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs26()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs26 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  26 bytes of parameters.                                                     ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs26   PROC
        SUB     SP, 30                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    26
RestoreRegs26   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs28()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs28 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  28 bytes of parameters.                                                     ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs28   PROC
        SUB     SP, 32                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    28
RestoreRegs28   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs30()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs30 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  30 bytes of parameters.                                                     ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs30   PROC
        SUB     SP, 34                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    30
RestoreRegs30   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs32()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs32 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  32 bytes of parameters.                                                     ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs32   PROC
        SUB     SP, 36                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    32
RestoreRegs32   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs34()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs34 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  34 bytes of parameters.                                                     ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs34   PROC
        SUB     SP, 38                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    34
RestoreRegs34   ENDP

CODE16  ENDS
ENDIF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                              ;
;  RestoreRegs36()                                                             ;
;                                                                              ;
;  Upon  entry EDX  contains the  segmented  address  of the  saved  registers ;
;  structure   because  of  T_RestoreReg16's   efforts  above.   RestoreRegs36 ;
;  restores the saved registers and returns  to the API caller for an API with ;
;  36 bytes of parameters.                                                     ;
;                                                                              ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

IFDEF T_16BIT
        ASSUME  CS:CODE16
CODE16  SEGMENT
        ALIGN   40H

RestoreRegs36   PROC
        SUB     SP, 40                          ; Skip parms and allocate CS:IP
        PUSH    BP                              ; Save BP
        MOV     BP,SP                           ; BP = Stack frame base pointer
        PUSH    DS                              ; Save DS
        PUSH    BX                              ; Save BX
        MOV     BX, DX                          ; BX = sRegs16 pointer offset
        ROR     EDX,16                          ; Switch segment and offset
        MOV     DS, DX                          ; DS = sRegs16 pointer segment
        MOV     ECX, DWORD PTR [BX].regs16_ulCSIP; ECX = API caller's return CS:IP
        MOV     DWORD PTR [BP+2], ECX           ; Return to API caller
        MOV     CX, WORD PTR [BX].regs16_usCX   ; Restore CX from sRegs16
        MOV     DX, WORD PTR [BX].regs16_usDX   ; Restore DX from sRegs16
        POP     BX                              ; Restore BX
        POP     DS                              ; Restore DS
        POP     BP                              ; Restore BP
        RETF    36
RestoreRegs36   ENDP

CODE16  ENDS
ENDIF
END
